services:
    db:
        build:
            context: .
            dockerfile_inline: |
                FROM postgres:12-alpine
                COPY create_tables.sql /docker-entrypoint-initdb.d/
        environment:
            POSTGRES_USER: freecodecamp
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: worldcup
        ports:
            - 5432:5432
        volumes:
            - type: bind
              source: ./
              target: /app
